# Generated by Django 5.1 on 2024-08-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=20)),
                ('faculty', models.CharField(choices=[('BCA', 'bca'), ('BBA', 'bba'), ('MCA', 'mca')], max_length=10)),
            ],
        ),
    ]
